#ifndef ITEM_ID_HPP
#define ITEM_ID_HPP

#include <cstdint>

enum class ItemID : int16_t
{
    iron_shovel = 256,
    iron_pickaxe,
    iron_axe,
    flint_and_steel,
    apple,
    bow,
    arrow,
    coal,
    diamond,
    iron,
    gold,
    iron_sword,
    wooden_sword,
    wooden_shovel,
    wooden_pickaxe,
    wooden_axe,
    stone_sword,
    stone_shovel,
    stone_pickaxe,
    stone_axe,
    diamond_sword,
    diamond_shovel,
    diamond_pickaxe,
    diamond_axe,
    stick,
    bowl,
    mushroom_stew,
    gold_sword,
    gold_shovel,
    gold_pickaxe,
    gold_axe,
    string,
    feather,
    gunpowder,
    wooden_hoe,
    stone_hoe,
    iron_hoe,
    diamond_hoe,
    gold_hoe,
    seeds,
    wheat,
    bread,
    leather_cap,
    leather_tunic,
    leather_pants,
    leather_boots,
    chainmail_helmet,
    chainmail_chestplate,
    chainmail_leggings,
    chainmail_boots,
    iron_helmet,
    iron_chestplate,
    iron_leggings,
    iron_boots,
    diamond_helmet,
    diamond_chestplate,
    diamond_leggings,
    diamond_boots,
    gold_helmet,
    gold_chestplate,
    gold_leggings,
    gold_boots,
    flint,
    porkchop,
    cooked_porkchop,
    painting,
    golden_apple,
    sign,
    door,
    bucket,
    water_bucket,
    lava_bucket,
    minecart,
    saddle,
    iron_door,
    redstone_dust,
    snowball,
    boat,
    leather,
    milk_bucket,
    brick,
    clay_ball,
    reeds,
    paper,
    book,
    slime_ball,
    chest_minecart,
    furnace_minecart,
    egg,
    compass,
    fishing_rod,
    clock,
    glowstone_dust,
    fish,
    cooked_fish,
    dye,
    bone,
    sugar,
    cake,
    bed,
    diode,
    record_13 = 2256,
    record_cat = 2257
};

constexpr int16_t operator+(ItemID e) noexcept
{
    return static_cast<int16_t>(e);
}

#endif